### ISSUE TITLE
[Task] Multiple similar targets can be found under /targets

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat#1252]
Not sure how to replicate, but sometimes multiple of the same targets can be found when querying the backend.

I assume it has something to do with https://github.com/cryostatio/cryostat/pull/1089 and the TargetNode db since only the jvmIds are different. Seems like targets aren't being cleaned up correctly somehow.

e,g,

```
$ http -v :8181/api/v1/targets 'Authorization: Basic dXNlcjpwYXNzCg'
```
```
[
    {
        "alias": "io.cryostat.Cryostat",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "io.cryostat.Cryostat",
                "PORT": "9091",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi",
        "jvmId": "71i3ivTX0ucC9BzsZTMd3ySSPX3q3azC-sgrs5-yV54=",
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9197/jmxrmi",
        "jvmId": "owjqR0mWhLKVLrezbSAi_hYWd8MNV8KeBEGvYks6aYg=",
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9097/jmxrmi",
        "jvmId": "80YtD5qmf5nD2GAxBZcwMObUHACaB8XdPIBYilG3oXQ=",
        "labels": {}
    },
    {
        "alias": "io.cryostat.Cryostat",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "io.cryostat.Cryostat",
                "PORT": "9091",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi",
        "jvmId": "43p-u3RxnzZ7K42EQG39k7T6JoRoin7a5sR56WZKRjM=",
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9197/jmxrmi",
        "jvmId": "GoMF-2GbZg7VEBVG5rVYHOiRREn69RkVopAkz9siR-U=",
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9197/jmxrmi",
        "jvmId": null,
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9097/jmxrmi",
        "jvmId": "WjpVmIxyP8oEHw_o2g5f0nsdAoax24Yi_2kuwyE8vvU=",
        "labels": {}
    },
    {
        "alias": "/deployments/quarkus-run.jar",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "/deployments/quarkus-run.jar",
                "PORT": "10000",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:10000/jmxrmi",
        "jvmId": "5WsWHFBe4fOV4dYw0YyNrPUWOKMGRu_rrETH9KuixSw=",
        "labels": {}
    },
    {
        "alias": "es.andrewazor.demo.Main",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "es.andrewazor.demo.Main",
                "PORT": "9094",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9094/jmxrmi",
        "jvmId": "mLUE0QmJgdDrCABMvm0SF13ai2CWACll3FP55v5f5UM=",
        "labels": {}
    },
    {
        "alias": "quarkus-test-agent",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "/deployments/quarkus-run.jar",
                "PID": "1",
                "PORT": "9898",
                "REALM": "quarkus-test-agent",
                "START_TIME": "1668625466"
            },
            "platform": {
                "INSTANCE_ID": "da604bc3-95f8-4878-969c-257cf40a9a70"
            }
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9898/jmxrmi",
        "jvmId": "Xsy9S7gL1x8D3NKQrGDPi-TmOnXSy-NXb-pEbp9ZuM4=",
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9197/jmxrmi",
        "jvmId": "pEZXi6wlH7dHseHkOD3guP3n_LD1UTs-Eich4khAHuk=",
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9097/jmxrmi",
        "jvmId": "eEzL3zFCkTWcmSX0d49abaBcxmnpDaZcftqACNrwlFk=",
        "labels": {}
    },
    {
        "alias": "es.andrewazor.demo.Main",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "es.andrewazor.demo.Main",
                "PORT": "9095",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9095/jmxrmi",
        "jvmId": "UjinnB7_TreqA93DiePBlckuKgAsl32N5_WtIbLnPyM=",
        "labels": {}
    },
    {
        "alias": "es.andrewazor.demo.Main",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "es.andrewazor.demo.Main",
                "PORT": "9093",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9093/jmxrmi",
        "jvmId": "GCqCg8f1WytzD_Hwn4VzpvKExPPymiheLUgmx-32hzo=",
        "labels": {}
    },
    {
        "alias": "es.andrewazor.demo.Main",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "es.andrewazor.demo.Main",
                "PORT": "9093",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9093/jmxrmi",
        "jvmId": "KPkEQYj9tQYCvL5nyGm35-Jx1WMM1fYhJwDz4sXj-RY=",
        "labels": {}
    },
    {
        "alias": "es.andrewazor.demo.Main",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "es.andrewazor.demo.Main",
                "PORT": "9094",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9094/jmxrmi",
        "jvmId": "daR2Yq_mOaILQ-DDyxYA9i3JEuuQDEI6HBvPCvbI03k=",
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9197/jmxrmi",
        "jvmId": "zL6x1yVlpJ99dbpdRnny1sXLUd8M-lMC_f6SV9Y_qtc=",
        "labels": {}
    },
    {
        "alias": "es.andrewazor.demo.Main",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "es.andrewazor.demo.Main",
                "PORT": "9095",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9095/jmxrmi",
        "jvmId": "OjSTjHEsvh_KOBSK51Cc5lwJWhgVhP_pfZjk2i-bG1Q=",
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9097/jmxrmi",
        "jvmId": null,
        "labels": {}
    },
    {
        "alias": "quarkus-test",
        "annotations": {
            "cryostat": {},
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9197/jmxrmi",
        "jvmId": "AX3L72jaB3z8jUEAL5qoDpdNLv2eqte9DzvEBaZzgr8=",
        "labels": {}
    },
    {
        "alias": "/deployments/quarkus-run.jar",
        "annotations": {
            "cryostat": {
                "HOST": "cryostat",
                "JAVA_MAIN": "/deployments/quarkus-run.jar",
                "PORT": "10000",
                "REALM": "JDP"
            },
            "platform": {}
        },
        "connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:10000/jmxrmi",
        "jvmId": "6D7czBsegTSQs4_JvFlV172qElLpPLA-tbaMKW9fx7k=",
        "labels": {}
    }
]
```

**Comment by andrewazores** [comment]
Do these apparent duplicates persist for a long time? I would expect this to happen if a target has been restarted and replaced in an environment like JDP discovery, where the newly appearing replacement will be added to the database before we recognize that the original instance has disappeared. But maybe this happens in some case like the whole pod containing Cryostat and the targets was stopped, so the database is left with the target definitions intact, and then on restart we notice new targets and add them as duplicates in the database?

**Comment by maxcao13** [comment]
> Do these apparent duplicates persist for a long time? I would expect this to happen if a target has been restarted and replaced in an environment like JDP discovery, where the newly appearing replacement will be added to the database before we recognize that the original instance has disappeared. But maybe this happens in some case like the whole pod containing Cryostat and the targets was stopped, so the database is left with the target definitions intact, and then on restart we notice new targets and add them as duplicates in the database?

They do persist for a long time, so I think it may be the latter case.

**Comment by maxcao13** [comment]
Interestingly, when I use postgres, this happens, but if I don't use any real database, it doesn't. So I think you are very right on this.

**Comment by andrewazores** [comment]
It happens with Postgres but not h2:file? It wouldn't happen with h2:mem since that database gets dropped when the pod stops, but it seems that Postgres and h2:file should behave similarly here...

**Comment by maxcao13** [comment]
> It happens with Postgres but not h2:file? It wouldn't happen with h2:mem since that database gets dropped when the pod stops, but it seems that Postgres and h2:file should behave similarly here...

I'm not sure what I did to cause this originally by using Postgres so I don't know how to recreate it with h2:file but I will try right now. Just restarting the instance doesn't seem to recreate it for me... So as of now, my postgres db is a bit messed up every time I load it up.

**Comment by maxcao13** [comment]
Not sure if this is related, but I get a lot of these messages with registering the new quarkus-test target after #1190 

```
Nov 16, 2022 7:41:51 PM io.cryostat.core.log.Logger warn
WARNING: HTTP 400: Failed to register new provider for "quarkus-test" @ "http://cryostat:10011/cryostat-discovery": Error while committing the transaction
io.vertx.ext.web.handler.HttpException: Bad Request
Caused by: io.cryostat.net.web.http.api.v2.ApiException: Failed to register new provider for "quarkus-test" @ "http://cryostat:10011/cryostat-discovery": Error while committing the transaction
        at io.cryostat.net.web.http.api.v2.DiscoveryRegistrationHandler.handle(DiscoveryRegistrationHandler.java:167)
        at io.cryostat.net.web.http.api.v2.AbstractV2RequestHandler.handle(AbstractV2RequestHandler.java:108)
        at io.cryostat.net.web.http.api.v2.AbstractV2RequestHandler.handle(AbstractV2RequestHandler.java:71)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.cryostat.discovery.RegistrationException: Failed to register new provider for "quarkus-test" @ "http://cryostat:10011/cryostat-discovery": Error while committing the transaction
        at io.cryostat.discovery.DiscoveryStorage.register(DiscoveryStorage.java:273)
        at io.cryostat.net.web.http.api.v2.DiscoveryRegistrationHandler.handle(DiscoveryRegistrationHandler.java:165)
        ... 11 more
Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:81)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
        at io.cryostat.storage.AbstractDao.save(AbstractDao.java:72)
        at io.cryostat.discovery.PluginInfoDao.save(PluginInfoDao.java:74)
        at io.cryostat.discovery.DiscoveryStorage.register(DiscoveryStorage.java:260)
        ... 12 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:65)
        ... 16 more
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
        at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3375)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3908)
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3303)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2438)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
        ... 15 more
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.UK_LFC8YJ7NOT9MTD4XYCNE72QEC_INDEX_5 ON PUBLIC.PLUGININFO(CALLBACK NULLS FIRST) VALUES ( /* 5 */ 'http://cryostat:10011/cryostat-discovery' )"; SQL statement:
/* insert io.cryostat.discovery.PluginInfo */ insert into PluginInfo (cal [23505-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
        at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
        at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
        at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
        at org.h2.command.dml.Insert.insertRows(Insert.java:174)
        at org.h2.command.dml.Insert.update(Insert.java:135)
        at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
        at org.h2.command.CommandContainer.update(CommandContainer.java:169)
        at org.h2.command.Command.executeUpdate(Command.java:252)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 35 more
Nov 16, 2022 7:41:51 PM org.slf4j.impl.JDK14LoggerAdapter fillCallerData
WARNING: 10.0.2.100 - - [Wed, 16 Nov 2022 19:41:51 GMT] 5ms "POST /api/v2.2/discovery HTTP/1.1" 400 213 bytes "-" "Apache-HttpClient/4.5.13 (Java/17.0.5)"
```

**Comment by andrewazores** [comment]
Could be related. Hopefully not, because that would imply not only is something wrong with the sample app setup that is causing the registration failures, but also that something is wrong in the discovery plugin implementation that is allowing bad registrations to still publish (duplicate) targets. But, it looks like the original JSON response with the duplicates also includes duplicates for targets other than `quarkus-test` ones, which don't really use the discovery plugin API other than through the internal JDP builtin.

**Comment by maxcao13** [comment]
I removed my previous Postgres instance and re-ran smoketest to solve the issues, but I will continue to monitor this problem so that I can consistently recreate it.

**Comment by maxcao13** [comment]
> I removed my previous Postgres instance and re-ran smoketest to solve the issues, but I will continue to monitor this problem so that I can consistently recreate it.

Ah, okay I just restarted a postgres instance and I see the problem popup. This does not happen with h2:file.

![image](https://user-images.githubusercontent.com/69827283/202281541-7abd3218-928d-4f65-aa0a-c5410b161e33.png)

**Comment by maxcao13** [comment]
Just to confirm, 
to run with postgres
`$ sh smoketest.sh postgres`
and now the default for smoketest is h2file so
`$ sh smoketest.sh` is by default running h2file
and to run the h2 in-memory db:
`$ sh smoketest.sh h2mem` ?

**Comment by andrewazores** [comment]
correct

**Comment by maxcao13** [comment]
It seems this is actually a problem in h2file as well. For some reason /targets is okay, but if you query `/api/v2.1/discovery`, then there will be a lot of duplicate 9097 and 9197 quarkus test targets.

What is happening is actually because of #1189. The jvmIds in the ServiceRef objects are being compared somewhere when updating `PluginInfos` . After reverting the `equals` method in ServiceRef, the problem gets resolved. 

I guess it would make sense that the `String subtree` would be different because of the jvmIds being different. But I'm also not sure how entirely new PluginInfos are being inserted in the first place, and how the database knew before this change, to replace the plugin children instead of adding new children.

**Comment by andrewazores** [comment]
Makes sense. Good investigation so far.
