### ISSUE TITLE
WebSocket ConcurrentModificationException

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#138]
```
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1542)
	at com.redhat.rhjmc.containerjfr.tui.ws.MessagingServer.flush(MessagingServer.java:131)
	at com.redhat.rhjmc.containerjfr.tui.ws.WsCommandExecutor.flush(WsCommandExecutor.java:113)
	at com.redhat.rhjmc.containerjfr.tui.ws.WsCommandExecutor.run(WsCommandExecutor.java:79)
	at com.redhat.rhjmc.containerjfr.ContainerJfr.main(ContainerJfr.java:69)
```

**Comment by andrewazores** [comment]
Looks like #114 again.
