### ISSUE TITLE
[Bug] `CRYOSTAT_DISABLE_BUILTIN_DISCOVERY` environment variable does not work

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1505]
## Current Behavior:
```
$ CRYOSTAT_DISABLE_BUILTIN_DISCOVERY=true sh run.sh
...
SEVERE: Exception thrown
java.util.NoSuchElementException: No selected platforms found. Available platforms: [io.cryostat.platform.internal.OpenShiftPlatformStrategy, io.cryostat.platform.internal.KubeApiPlatformStrategy, io.cryostat.platform.internal.PodmanPlatformStrategy, io.cryostat.platform.internal.DefaultPlatformStrategy]
	at io.cryostat.platform.PlatformModule.lambda$providePlatformStrategy$8(PlatformModule.java:160)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.cryostat.platform.PlatformModule.providePlatformStrategy(PlatformModule.java:157)
	at io.cryostat.platform.PlatformModule_ProvidePlatformStrategyFactory.providePlatformStrategy(PlatformModule_ProvidePlatformStrategyFactory.java:53)
	at io.cryostat.platform.PlatformModule_ProvidePlatformStrategyFactory.get(PlatformModule_ProvidePlatformStrategyFactory.java:41)
	at io.cryostat.platform.PlatformModule_ProvidePlatformStrategyFactory.get(PlatformModule_ProvidePlatformStrategyFactory.java:14)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at io.cryostat.platform.PlatformModule_ProvideAuthManagerFactory.get(PlatformModule_ProvideAuthManagerFactory.java:50)
	at io.cryostat.platform.PlatformModule_ProvideAuthManagerFactory.get(PlatformModule_ProvideAuthManagerFactory.java:16)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at io.cryostat.DaggerCryostat_Client$ClientImpl.recordingMetadataLabelsPostHandler(DaggerCryostat_Client.java:976)
	at io.cryostat.DaggerCryostat_Client$ClientImpl.setOfRequestHandler(DaggerCryostat_Client.java:1445)
	at io.cryostat.DaggerCryostat_Client$ClientImpl.webServer(DaggerCryostat_Client.java:1747)
	at io.cryostat.Cryostat.lambda$start$1(Cryostat.java:97)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

## Expected Behavior:
Setting this environment variable should disable all built-in discovery mechanisms other than Custom Targets.

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/blob/f9a7f00f5576a2a81a22ff06a47f0ce20523a5f5/src/main/java/io/cryostat/platform/PlatformModule.java#L125

This causes list of selected strategies to be completely empty.

That list is injected here:

https://github.com/cryostatio/cryostat/blob/f9a7f00f5576a2a81a22ff06a47f0ce20523a5f5/src/main/java/io/cryostat/platform/PlatformModule.java#L157

Currently, Custom Targets is supposed to be special-cased in like this:

https://github.com/cryostatio/cryostat/blob/f9a7f00f5576a2a81a22ff06a47f0ce20523a5f5/src/main/java/io/cryostat/discovery/BuiltInDiscovery.java#L68

However, since the Custom Targets platform client is not associated with any platform Strategy, we have this scenario where at least one other Strategy must be selected.

If there were a Custom Targets Strategy that were always available this could simplify some code, and it could be special-cased in the Platform Module instead of in the BuiltInDiscovery.
