### ISSUE TITLE
[Bug] Tests fail with JDK 21

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#179]
### Current Behavior

Tests fail when run on JDK 21. This is intentionally ignored by CI for now:

https://github.com/cryostatio/cryostat3/pull/102

### Expected Behavior

Tests should pass on JDK 21 and 17 alike.

### Anything else?

```
Error: ]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#enhancerDomainObjects threw an exception: org.hibernate.bytecode.enhance.spi.EnhancementException: Failed to enhance class io.quarkus.hibernate.orm.panache.PanacheEntity
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:157)
	at io.quarkus.hibernate.orm.deployment.HibernateEntityEnhancer.enhance(HibernateEntityEnhancer.java:101)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.enhanceEntities(HibernateOrmProcessor.java:1266)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.enhancerDomainObjects(HibernateOrmProcessor.java:627)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.IllegalArgumentException: Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:96)
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:855)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:841)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$001(TypePool.java:921)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1019)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1088)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getTypeVariables(TypeDescription.java:8448)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isGenerified(TypeDescription.java:8059)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying.onNonGenericType(TypeDescription.java:1707)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying$1.onNonGenericType(TypeDescription.java:1663)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3672)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6222)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:698)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:712)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:679)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:698)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:712)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:637)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:527)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.lambda$resolveGetter$0(ByteBuddyEnhancementContext.java:94)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.resolveGetter(ByteBuddyEnhancementContext.java:93)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.getGetter(EnhancerImpl.java:545)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.doGetAnnotations(EnhancerImpl.java:574)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.getAnnotations(EnhancerImpl.java:553)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.hasAnnotation(EnhancerImpl.java:503)
	at org.hibernate.bytecode.enhance.spi.DefaultEnhancementContext.isPersistentField(DefaultEnhancementContext.java:103)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.isPersistentField(ByteBuddyEnhancementContext.java:68)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.PersistentAttributeTransformer.collectPersistentFields(PersistentAttributeTransformer.java:123)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.createTransformer(EnhancerImpl.java:384)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.doEnhance(EnhancerImpl.java:371)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.lambda$enhance$0(EnhancerImpl.java:151)
	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.rewrite(ByteBuddyState.java:163)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:151)
	... 12 more
```

Looks like this needs a Quarkus update.

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat3/pull/176#issuecomment-1821801628

https://github.com/cryostatio/cryostat3/pull/160#issuecomment-1817169564
