### ISSUE TITLE
[Bug] Unable to create short form custom target

### ISSUE THREAD

**Issue by cmah88** [cryostatio/cryostat#1867]
### Current Behavior

java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost: caused by URISyntaxException: Expected scheme-specific part at index 10: localhost:

![image](https://github.com/cryostatio/cryostat/assets/97625933/e6318b83-2488-4eab-88e0-fc0b96455057)

![image](https://github.com/cryostatio/cryostat/assets/97625933/9f4145a2-622c-4638-80d9-1bf53dc40d9d)

### Environment

```Markdown
- OS: 
- Environment: 
- Version:
```

**Comment by andrewazores** [comment]
Creating a custom target with `localhost:0` results in a target discovery notification, but also immediately an error notification with the 500 response.

It may actually be that the 500 response is occurring in response to the request to list event templates, not the target creation. So perhaps the exception is really happening when Cryostat tries to use this custom target definition to open a JMX connection - is it no longer looking at these "short form" connection URLs and trying to format them into `service:jmx:rmi:` JMX URLs?

**Comment by andrewazores** [comment]
@Josh-Matsuoka @aali309 @mwangggg could one of you take a look at this next week?

**Comment by aali309** [comment]
> Creating a custom target with `localhost:0` results in a target discovery notification, but also immediately an error notification with the 500 response.
> 
> It may actually be that the 500 response is occurring in response to the request to list event templates, not the target creation. So perhaps the exception is really happening when Cryostat tries to use this custom target definition to open a JMX connection - is it no longer looking at these "short form" connection URLs and trying to format them into `service:jmx:rmi:` JMX URLs?

Yes, that could be the reason. Target is being created and discovered but listing event templates produces
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)   https://localhost:8181/api/v1/targets/localhost%3A0/templates`

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/blob/050e03f5390e44adaeae6161ec5e4b7afc476437/src/main/java/io/cryostat/net/TargetConnectionManager.java#L215

Looks like the root cause is here. This should catch `URISyntaxException`, not only `MalformedURLException`. This way if the connection attempt using the raw short-form string fails for that reason it will try to create the full `service:jmx:rmi` URL using the short form.

**Comment by andrewazores** [comment]
Here's the server stack trace from when this happens:

```
SEVERE: HTTP 500: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
io.vertx.ext.web.handler.HttpException: Internal Server Error
Caused by: java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
	at io.cryostat.configuration.CredentialsManager.getCredentialsByTargetId(CredentialsManager.java:186)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.getConnectionDescriptorFromContext(AbstractAuthenticatedRequestHandler.java:142)
	at io.cryostat.net.web.http.api.v1.TargetRecordingsGetHandler.handleAuthenticated(TargetRecordingsGetHandler.java:103)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:81)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:51)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2982)
	at java.base/java.net.URI$Parser.parse(URI.java:3182)
	at java.base/java.net.URI.<init>(URI.java:623)
	at org.apache.http.client.utils.URIBuilder.build(URIBuilder.java:146)
	at io.cryostat.configuration.CredentialsManager.getCredentialsByTargetId(CredentialsManager.java:177)
	... 13 more
```

**Comment by andrewazores** [comment]
That was after defining a custom target with the short-form `localhost:0` and then clicking on the Recordings navigation item in the UI. When clicking on Events it's similar:

```
SEVERE: HTTP 500: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
io.vertx.ext.web.handler.HttpException: Internal Server Error
Caused by: io.cryostat.net.web.http.api.v2.ApiException: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
	at io.cryostat.net.web.http.api.v2.AbstractV2RequestHandler.handle(AbstractV2RequestHandler.java:99)
	at io.cryostat.net.web.http.api.v2.AbstractV2RequestHandler.handle(AbstractV2RequestHandler.java:49)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
	at io.cryostat.configuration.CredentialsManager.getCredentialsByTargetId(CredentialsManager.java:186)
	at io.cryostat.net.web.http.api.v2.AbstractV2RequestHandler.getConnectionDescriptorFromParams(AbstractV2RequestHandler.java:151)
	at io.cryostat.net.web.http.api.v2.TargetProbesGetHandler.handle(TargetProbesGetHandler.java:93)
	at io.cryostat.net.web.http.api.v2.AbstractV2RequestHandler.handle(AbstractV2RequestHandler.java:86)
	... 10 more
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2982)
	at java.base/java.net.URI$Parser.parse(URI.java:3182)
	at java.base/java.net.URI.<init>(URI.java:623)
	at org.apache.http.client.utils.URIBuilder.build(URIBuilder.java:146)
	at io.cryostat.configuration.CredentialsManager.getCredentialsByTargetId(CredentialsManager.java:177)
	... 13 more
```
