### ISSUE TITLE
[Bug] Unable to archive recordings for short form custom target

### ISSUE THREAD

**Issue by aali309** [cryostatio/cryostat#1876]
### Current Behavior

Archiving recordings using short form custom target produces:

`SEVERE: HTTP 500: java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
io.vertx.ext.web.handler.HttpException: Internal Server Error
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.cryostat.net.web.http.api.v1.TargetRecordingPatchSave.handle(TargetRecordingPatchSave.java:47)
	at io.cryostat.net.web.http.api.v1.TargetRecordingPatchHandler.handleAuthenticated(TargetRecordingPatchHandler.java:102)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:81)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:51)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
	at io.cryostat.configuration.CredentialsManager.getCredentialsByTargetId(CredentialsManager.java:202)
	at io.cryostat.recordings.JvmIdHelper.computeJvmId(JvmIdHelper.java:164)
	at io.cryostat.recordings.JvmIdHelper$IdLoader.asyncLoad(JvmIdHelper.java:239)
	at io.cryostat.recordings.JvmIdHelper$IdLoader.asyncLoad(JvmIdHelper.java:235)
	at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.lambda$newMappingFunction$0(LocalAsyncLoadingCache.java:68)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache.lambda$get$2(LocalAsyncCache.java:94)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:294)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:290)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:92)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:83)
	at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:134)
	at io.cryostat.recordings.JvmIdHelper.getJvmId(JvmIdHelper.java:181)
	at io.cryostat.recordings.JvmIdHelper.getJvmId(JvmIdHelper.java:175)
	at io.cryostat.recordings.RecordingArchiveHelper.writeRecordingToDestination(RecordingArchiveHelper.java:897)
	at io.cryostat.recordings.RecordingArchiveHelper.lambda$saveRecording$1(RecordingArchiveHelper.java:376)
	at io.cryostat.net.TargetConnectionManager.executeConnectedTask(TargetConnectionManager.java:151)
	at io.cryostat.recordings.RecordingArchiveHelper.saveRecording(RecordingArchiveHelper.java:369)
	at io.cryostat.net.web.http.api.v1.TargetRecordingPatchSave.handle(TargetRecordingPatchSave.java:46)
	... 12 more
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 10: localhost:
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2982)
	at java.base/java.net.URI$Parser.parse(URI.java:3182)
	at java.base/java.net.URI.<init>(URI.java:623)
	at org.apache.http.client.utils.URIBuilder.build(URIBuilder.java:146)
	at io.cryostat.configuration.CredentialsManager.getCredentialsByTargetId(CredentialsManager.java:193)
	... 30 more
`

![image](https://github.com/cryostatio/cryostat/assets/56743004/1bf510e8-234f-46e7-bfb8-4d336a389de9)

### Environment

```Markdown
- OS: 
- Environment: 
- Version:
```

**Comment by andrewazores** [comment]
I think this was a duplicate of #1867, right? Same root cause

**Comment by aali309** [comment]
> I think this was a duplicate of #1867, right? Same root cause

Yes. the fix for #1867 covered this as well.
