### ISSUE TITLE
itest FlightRecorderException: Failed updating the recording options for Snapshot

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#636]
```
io.vertx.ext.web.handler.impl.HttpStatusException: Internal Server Error
Caused by: org.openjdk.jmc.rjmx.services.jfr.FlightRecorderException: Failed updating the recording options for Snapshot
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.updateRecordingOptions(FlightRecorderServiceV2.java:447)
	at io.cryostat.net.web.http.api.v1.TargetSnapshotPostHandler.lambda$handleAuthenticated$0(TargetSnapshotPostHandler.java:118)
	at io.cryostat.net.TargetConnectionManager.executeConnectedTask(TargetConnectionManager.java:128)
	at io.cryostat.net.web.http.api.v1.TargetSnapshotPostHandler.handleAuthenticated(TargetSnapshotPostHandler.java:101)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:90)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:65)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.management.RuntimeMBeanException: java.lang.IllegalStateException: Recording option disk can't be changed after recording has started
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:829)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:842)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:811)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1021)
	at org.openjdk.jmc.rjmx.internal.MCMBeanServerConnection.invoke(MCMBeanServerConnection.java:259)
	at org.openjdk.jmc.rjmx.ConnectionToolkit.invokeOperation(ConnectionToolkit.java:196)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderCommunicationHelperV2.invokeJfrOperation(FlightRecorderCommunicationHelperV2.java:91)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderCommunicationHelperV2.invokeOperation(FlightRecorderCommunicationHelperV2.java:82)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.updateRecordingOptions(FlightRecorderServiceV2.java:453)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.updateRecordingOptions(FlightRecorderServiceV2.java:445)
	... 12 more
Caused by: java.lang.IllegalStateException: Recording option disk can't be changed after recording has started
	at jdk.jfr/jdk.jfr.internal.PlatformRecording.setToDisk(PlatformRecording.java:442)
	at jdk.jfr/jdk.jfr.Recording.setToDisk(Recording.java:532)
	at jdk.management.jfr/jdk.management.jfr.FlightRecorderMXBeanImpl.lambda$setRecordingOptions$2(FlightRecorderMXBeanImpl.java:292)
	at jdk.management.jfr/jdk.management.jfr.FlightRecorderMXBeanImpl.setOption(FlightRecorderMXBeanImpl.java:351)
	at jdk.management.jfr/jdk.management.jfr.FlightRecorderMXBeanImpl.setRecordingOptions(FlightRecorderMXBeanImpl.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at java.management/com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at java.management/javax.management.StandardMBean.invoke(StandardMBean.java:405)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

[cryostat-itest-2021-08-10T13:41:15Z.log](https://github.com/cryostatio/cryostat/files/6962154/cryostat-itest-2021-08-10T13.41.15Z.log)

```
[INFO] --- maven-failsafe-plugin:2.22.2:integration-test (failsafe-tests) @ cryostat ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running itest.UploadCertificateIT
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 409: Conflict
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.705 s - in itest.UploadCertificateIT
[INFO] Running itest.InterleavedExternalTargetRequestsIT
[INFO] [stdout] {"datasourceAvailable":true,"dashboardAvailable":true}[podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9099, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] fa508e552b359190e5dcb4a5a6f79347ea6a47f7a8733458683ab7d27b30eb12
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9098, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] 75b01acd99bae3ba6c007273008df3bfb3796bfb62c1f6a4880e17160185d429
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9100, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] 79d907ab32f7caad5df6284f57db38807d9d32e887a156b363c9e9c038c45318
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9095, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] cda9ecc6ec0792485cc76a2bec41406018e0160db2c48d319fb01f8f7e87c353
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9093, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] 7aee7d4ff43e8282e65e0eb6f16678e5a5afa645acc077123232f0d3fbb6a515
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9096, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] 09aed55e12e95d88f9a9767f4072119c19685d67e28bb33fc00cdcebd3cf497b
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9097, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] 9940225f33d00eb01e8a3fdde3e508944ffda192b57e2e60739478698c868948
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9094, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] 46670f5da5d99392bf01f39577a620763963bef5fa4192d5ffae17ab50420766
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", 75b01acd99bae3ba6c007273008df3bfb3796bfb62c1f6a4880e17160185d429]
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", 7aee7d4ff43e8282e65e0eb6f16678e5a5afa645acc077123232f0d3fbb6a515]
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", 09aed55e12e95d88f9a9767f4072119c19685d67e28bb33fc00cdcebd3cf497b]
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", cda9ecc6ec0792485cc76a2bec41406018e0160db2c48d319fb01f8f7e87c353]
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", 79d907ab32f7caad5df6284f57db38807d9d32e887a156b363c9e9c038c45318]
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", 9940225f33d00eb01e8a3fdde3e508944ffda192b57e2e60739478698c868948]
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", fa508e552b359190e5dcb4a5a6f79347ea6a47f7a8733458683ab7d27b30eb12]
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", 46670f5da5d99392bf01f39577a620763963bef5fa4192d5ffae17ab50420766]
[INFO] [stdout] "running"
[INFO] [stdout] "running"
[INFO] [stdout] "running"
[INFO] [stdout] "running"
[INFO] [stdout] "running"
[INFO] [stdout] "running"
[INFO] [stdout] "running"
[INFO] [stdout] "running"
[WARN] [stderr] 6/9 targets found - waiting for discovery to complete
[INFO] [stdout] expected target count (9) observed, counting success 1/3
[INFO] [stdout] expected target count (9) observed, counting success 2/3
[INFO] [stdout] expected target count (9) observed, counting success 3/3
[INFO] [stdout] discovery complete
[INFO] [stdout] discovery completed in 22708ms
[INFO] [stdout] Elapsed time: 10158ms
[INFO] [stdout] [podman, kill, fa508e552b359190e5dcb4a5a6f79347ea6a47f7a8733458683ab7d27b30eb12]
[INFO] [stdout] fa508e552b359190e5dcb4a5a6f79347ea6a47f7a8733458683ab7d27b30eb12
[INFO] [stdout] [podman, kill, 75b01acd99bae3ba6c007273008df3bfb3796bfb62c1f6a4880e17160185d429]
[INFO] [stdout] 75b01acd99bae3ba6c007273008df3bfb3796bfb62c1f6a4880e17160185d429
[INFO] [stdout] [podman, kill, 79d907ab32f7caad5df6284f57db38807d9d32e887a156b363c9e9c038c45318]
[INFO] [stdout] 79d907ab32f7caad5df6284f57db38807d9d32e887a156b363c9e9c038c45318
[INFO] [stdout] [podman, kill, cda9ecc6ec0792485cc76a2bec41406018e0160db2c48d319fb01f8f7e87c353]
[INFO] [stdout] cda9ecc6ec0792485cc76a2bec41406018e0160db2c48d319fb01f8f7e87c353
[INFO] [stdout] [podman, kill, 7aee7d4ff43e8282e65e0eb6f16678e5a5afa645acc077123232f0d3fbb6a515]
[INFO] [stdout] 7aee7d4ff43e8282e65e0eb6f16678e5a5afa645acc077123232f0d3fbb6a515
[INFO] [stdout] [podman, kill, 09aed55e12e95d88f9a9767f4072119c19685d67e28bb33fc00cdcebd3cf497b]
[INFO] [stdout] 09aed55e12e95d88f9a9767f4072119c19685d67e28bb33fc00cdcebd3cf497b
[INFO] [stdout] [podman, kill, 9940225f33d00eb01e8a3fdde3e508944ffda192b57e2e60739478698c868948]
[INFO] [stdout] 9940225f33d00eb01e8a3fdde3e508944ffda192b57e2e60739478698c868948
[INFO] [stdout] [podman, kill, 46670f5da5d99392bf01f39577a620763963bef5fa4192d5ffae17ab50420766]
[INFO] [stdout] 46670f5da5d99392bf01f39577a620763963bef5fa4192d5ffae17ab50420766
[WARN] [stderr] 9 targets found - too many (expected 1)! Waiting to see if JDP settles...
[WARN] [stderr] 9 targets found - too many (expected 1)! Waiting to see if JDP settles...
[INFO] [stdout] expected target count (1) observed, counting success 1/3
[INFO] [stdout] expected target count (1) observed, counting success 2/3
[INFO] [stdout] expected target count (1) observed, counting success 3/3
[INFO] [stdout] discovery complete
[INFO] [stdout] discovery completed in 30035ms
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 67.136 s - in itest.InterleavedExternalTargetRequestsIT
[INFO] Running itest.RulesPostFormIT
[WARN] [stderr] HTTP 409: Conflict
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.247 s - in itest.RulesPostFormIT
[INFO] Running itest.UploadRecordingIT
[WARN] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.992 s - in itest.UploadRecordingIT
[INFO] Running itest.TargetRecordingOptionsIT
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.7 s - in itest.TargetRecordingOptionsIT
[INFO] Running itest.RecordingWorkflowIT
[WARN] [stderr] HTTP 500: Internal Server Error
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.77 s <<< FAILURE! - in itest.RecordingWorkflowIT
[ERROR] testWorkflow  Time elapsed: 2.77 s  <<< ERROR!
java.util.concurrent.ExecutionException: io.vertx.ext.web.handler.impl.HttpStatusException: Internal Server Error
	at itest.RecordingWorkflowIT.testWorkflow(RecordingWorkflowIT.java:136)
Caused by: io.vertx.ext.web.handler.impl.HttpStatusException: Internal Server Error
[INFO] Running itest.RulesPostJsonIT
[WARN] [stderr] HTTP 415: Unsupported Media Type
[WARN] [stderr] HTTP 409: Conflict
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 415: Unsupported Media Type
[WARN] [stderr] HTTP 400: Bad Request
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.125 s - in itest.RulesPostJsonIT
[INFO] Running itest.MessagingServerIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 s - in itest.MessagingServerIT
[INFO] Running itest.ClientAssetsIT
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.216 s - in itest.ClientAssetsIT
[INFO] Running itest.NotificationsUrlIT
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 s - in itest.NotificationsUrlIT
[INFO] Running itest.CryostatTemplateIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.301 s - in itest.CryostatTemplateIT
[INFO] Running itest.DiscoveryIT
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, JMX_PORT=9093, quay.io/andrewazores/vertx-fib-demo:0.7.0]
[INFO] [stdout] ab77a7cd1fcf56af4bca5e02deca4cc4d6f04bd8f0957527ce9f81a6c8a5816c
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", ab77a7cd1fcf56af4bca5e02deca4cc4d6f04bd8f0957527ce9f81a6c8a5816c]
[INFO] [stdout] "running"
[WARN] [stderr] 1/2 targets found - waiting for discovery to complete
[INFO] [stdout] expected target count (2) observed, counting success 1/3
[INFO] [stdout] expected target count (2) observed, counting success 2/3
[INFO] [stdout] expected target count (2) observed, counting success 3/3
[INFO] [stdout] discovery complete
[INFO] [stdout] discovery completed in 22530ms
[INFO] [stdout] [podman, kill, ab77a7cd1fcf56af4bca5e02deca4cc4d6f04bd8f0957527ce9f81a6c8a5816c]
[INFO] [stdout] ab77a7cd1fcf56af4bca5e02deca4cc4d6f04bd8f0957527ce9f81a6c8a5816c
[WARN] [stderr] 2 targets found - too many (expected 1)! Waiting to see if JDP settles...
[WARN] [stderr] 2 targets found - too many (expected 1)! Waiting to see if JDP settles...
[INFO] [stdout] expected target count (1) observed, counting success 1/3
[INFO] [stdout] expected target count (1) observed, counting success 2/3
[INFO] [stdout] expected target count (1) observed, counting success 3/3
[INFO] [stdout] discovery complete
[INFO] [stdout] discovery completed in 30030ms
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 53.159 s - in itest.DiscoveryIT
[INFO] Running itest.ApiListingIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.034 s - in itest.ApiListingIT
[INFO] Running itest.TemplatePostDeleteIT
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 s - in itest.TemplatePostDeleteIT
[INFO] Running itest.GrafanaSetupIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 s - in itest.GrafanaSetupIT
[INFO] Running itest.TargetEventsGetIT
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.127 s - in itest.TargetEventsGetIT
[INFO] Running itest.AutoRulesIT
[WARN] [stderr] HTTP 400: Bad Request
[INFO] [stdout] [podman, run, --quiet, --pod=cryostat-itests, --detach, --rm, --env, USE_AUTH=true, --env, JMX_PORT=9093, quay.io/andrewazores/vertx-fib-demo:0.6.0]
[INFO] [stdout] c42675482cb5a9352c0e632389978e375243d725ef0e786209555632b0ab4fec
[INFO] [stdout] [podman, container, inspect, --format="{{.State.Status}}", c42675482cb5a9352c0e632389978e375243d725ef0e786209555632b0ab4fec]
[INFO] [stdout] "running"
[WARN] [stderr] HTTP 404: Not Found
[WARN] [stderr] HTTP 404: Not Found
[INFO] [stdout] [podman, kill, c42675482cb5a9352c0e632389978e375243d725ef0e786209555632b0ab4fec]
[INFO] [stdout] c42675482cb5a9352c0e632389978e375243d725ef0e786209555632b0ab4fec
[WARN] [stderr] 2 targets found - too many (expected 1)! Waiting to see if JDP settles...
[WARN] [stderr] 2 targets found - too many (expected 1)! Waiting to see if JDP settles...
[INFO] [stdout] expected target count (1) observed, counting success 1/3
[INFO] [stdout] expected target count (1) observed, counting success 2/3
[INFO] [stdout] expected target count (1) observed, counting success 3/3
[INFO] [stdout] discovery complete
[INFO] [stdout] discovery completed in 30025ms
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 40.765 s - in itest.AutoRulesIT
[INFO] Running itest.TargetRecordingsClientErrorIT
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 404: Not Found
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 404: Not Found
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 404: Not Found
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 404: Not Found
[WARN] [stderr] HTTP 400: Bad Request
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.229 s - in itest.TargetRecordingsClientErrorIT
[INFO] Running itest.TargetPostDeleteIT
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 404: Not Found
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 s - in itest.TargetPostDeleteIT
[INFO] Running itest.ReportIT
[WARN] [stderr] HTTP 404: Not Found
[WARN] [stderr] HTTP 500: Internal Server Error
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.755 s <<< FAILURE! - in itest.ReportIT
[ERROR] testGetReportShouldSendFile  Time elapsed: 0.748 s  <<< ERROR!
java.util.concurrent.ExecutionException: io.vertx.ext.web.handler.impl.HttpStatusException: Internal Server Error
	at itest.ReportIT.testGetReportShouldSendFile(ReportIT.java:180)
Caused by: io.vertx.ext.web.handler.impl.HttpStatusException: Internal Server Error
[INFO] Running itest.CredentialsIT
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 400: Bad Request
[WARN] [stderr] HTTP 404: Not Found
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.128 s - in itest.CredentialsIT
[INFO] Running itest.NoopAuthIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in itest.NoopAuthIT
[INFO] Running itest.SnapshotIT
[WARN] [stderr] HTTP 404: Not Found
[WARN] [stderr] HTTP 500: Internal Server Error
[WARN] [stderr] HTTP 500: Internal Server Error
```

**Comment by andrewazores** [comment]
I haven't seen this in a long time.
