### ISSUE TITLE
NPE building ServiceRef

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat#699]
Ran into this while testing in Minikube.

```
WARNING: Exception thrown
java.lang.NullPointerException
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:496)
	at java.base/java.util.HashMap.putAll(HashMap.java:780)
	at io.cryostat.platform.ServiceRef.setPlatformAnnotations(ServiceRef.java:83)
	at io.cryostat.platform.internal.KubeApiPlatformClient$TargetTuple.toServiceRef(KubeApiPlatformClient.java:345)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.cryostat.platform.internal.KubeApiPlatformClient.getServiceRefs(KubeApiPlatformClient.java:313)
	at io.cryostat.platform.internal.KubeApiPlatformClient$1.eventReceived(KubeApiPlatformClient.java:114)
	at io.cryostat.platform.internal.KubeApiPlatformClient$1.eventReceived(KubeApiPlatformClient.java:101)
	at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:145)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$TypedWatcherWebSocketListener.onMessage(WatchConnectionManager.java:83)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by andrewazores** [comment]
`at io.cryostat.platform.internal.KubeApiPlatformClient$TargetTuple.toServiceRef(KubeApiPlatformClient.java:345)`:

```java
serviceRef.setPlatformAnnotations(podRef.getMetadata().getAnnotations());
```

Looks like the cause was that the Kubernetes resource's `.metadata.annotations` was null, rather than a (empty?) map. Was this bug repeatedly reproducible? I'm not sure if a null annotations field is normal or expected. Regardless, we should probably be checking nullness on all of these OpenShift/Kubernetes API client responses and handling them appropriately - in this case, that probably means just treating null as if it were an empty map.

**Comment by ebaron** [comment]
It was reproducible. Not sure how we haven't encountered this before.

**Comment by ebaron** [comment]
It seems our test applications automatically get the following annotations when deployed to OpenShift:
```yaml
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.217.0.19"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.217.0.19"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: restricted
```

This explains how we haven't seen this come up.

**Comment by andrewazores** [comment]
I'll take a look today.
